cluster:    
    job_bwa: "--time=10:00:00 --mem=80G  --cpus-per-task=40  --gres=lscratch:200"
    job_macs2: "--time=10:00:00 --mem=32G  --cpus-per-task=1  --gres=lscratch:100"
    job_rose: "--time=20:00:00 --mem=32G  --cpus-per-task=1  --gres=lscratch:100"
    job_motif: "--time=10:00:00 --mem=48G  --cpus-per-task=24  --gres=lscratch:100"
version:
    bwa: "0.7.17"    
    macs: "2.2.6"
    deeptools: "3.4.2"
    igvtools: "2.8.2"
    homer: "4.11.1"
    rose: "20200707"
    bamliquidator: "1.3.8"
hg38:
    bwa_index: "/data/Clinomics/Ref/khanlab/Index/BWAIndex/hg38"
    black_list: ref/ENCFF356LFX.bed
    tad_file: ref/A549_raw-merged_TADs.txt
    exclude_chr_list: ref/exclude_chr_list.txt
    macs2_gsize: 3.05e9
    gene_bed: ref/hg38.genes.bed
    tss_bed: ref/hg38.tss.bed
    rose: annotation/hg38_refseq.ucsc
    
hg19:
    bwa_index: "/data/Clinomics/Ref/khanlab/Index/BWAIndex/hg19"
    black_list: ref/wgEncodeDacMapabilityConsensusExcludable.bed
    tad_file: ref/tad.hg19.bed
    exclude_chr_list: ref/exclude_chr_list.txt
    macs2_gsize: 2.7e9
    gene_bed: ref/hg19.genes.bed
    tss_bed: ref/hg19.tss.bed
    rose: annotation/hg19_refseq.ucsc
mm10:
    bwa_index: /fdb/igenomes/Mus_musculus/UCSC/mm10/Sequence/BWAIndex/genome
    black_list: ref/ENCFF547MET.bed
    tad_file: ref/Myoblast.Doynova_2017-raw.domains
    rose: annotation/mm10_refseq.ucsc
default_lib_length: 148
min_mapq: "30"
bin_size: "25"
smooth_size: "75"
dup_cutoff: 0.3
macs2:
    peak_types: ["narrow","broad"]
    pvalues: [0.0000001, 0.00000000001]
    qvalues: [0.01,0.001]
rose:
    tss_distance: 2500
    stitch_distance: 12500
homer:
    motif_size: 1000
eden:
    TPM_cutoff: 4
    super_loci_distance_cutoff: 300000
    nearest_gene_distance_cutoff: 1500000
    exp_file: cufflinks_UCSC/genes.fpkm_tracking
coltron:
    path: /data/khanlab/apps/coltron/1.0.2/bin/coltron_berkley
    path_noexp: /data/khanlab/apps/coltron/1.0.2/bin/coltron
    nearest_tf_distance_cutoff: 500000
    exp_cutoff: 4
    exp_type: TPM
    

