%YAML 1.2
---
cluster:
    job_xenofilter: "--time=10:00:00 --mem=80G  --cpus-per-task=2"
    job_xenome: "--time=24:00:00 --mem=100G  --cpus-per-task=16"
    job_xengsort: "--time=24:00:00 --mem=80G  --cpus-per-task=30"
    job_star: "--time=30:00:00 --mem=200G  --cpus-per-task=30"
    job_rsem: "--time=10:00:00 --mem=200G  --cpus-per-task=30"
    job_seq2hla: "   --time=24:00:00 --mem=32G  --cpus-per-task=8"
    job_hlaminer: "   --time=24:00:00 --mem=32G  --cpus-per-task=8"
version:
    star: "2.7.3a"
    xenome: "1.0.1"    
    bowtie: "1.1.1"
    rsem: "1.3.0"
    HLAminer: "1.3.1"
annotations:
    - gencode
    - ucsc
hg38:
    star_index_gencode: "/data/Clinomics/Ref/khanlab/Index/STAR_GencodeV32_2_7_3a/"
    star_index_ucsc: /fdb/STAR_indices/2.7.3a/UCSC/hg38/genes-100/
    rsem_ref_gencode: /data/Clinomics/Ref/khanlab/Index/RSEM_GencodeV32/hg38
    rsem_ref_ucsc: "/data/Clinomics/Ref/khanlab/Index/RSEM_UCSC_hg38/hg38"
    hla_ref : "/data/Clinomics/Ref/khanlab/HLA/"
    xengsort_ref: "/data/Clinomics/Ref/xengsort/xengsort-index-k25.hg38.mm10.h5"
    
hg19:
    star_index_gencode: "/data/Clinomics/Ref/khanlab/Index/STAR_GencodeV19_2_7_3a/"
    star_index_ucsc: "/data/Clinomics/Ref/khanlab/Index/STAR_UCSC_hg19_2_7_3a/"
    rsem_ref_gencode: "/data/Clinomics/Ref/khanlab/Index/RSEM_GencodeV19/hg19"
    rsem_ref_ucsc: "/data/Clinomics/Ref/khanlab/Index/RSEM_UCSC_hg19/hg19"
    xenome_ref: "/fdb/xenome/idx"
    hla_ref : "/data/Clinomics/Ref/khanlab/HLA/"
    xengsort_ref: "/data/Clinomics/Ref/khanlab/Index/xengsort/xengsort-index-k25.hg38.mm10.h5"
mm10:
    star_index_gencode: "/fdb/STAR_indices/2.7.3a/GENCODE/Gencode_mouse/release_M16/genes-100"
    star_index_ucsc: "/fdb/STAR_indices/2.7.3a/UCSC/mm10/genes-100"
    rsem_ref_gencode: "/fdb/rsem/ref_from_genome/mouse_ref_GRCm38.82"
    rsem_ref_ucsc: "/fdb/rsem/ref_from_genome/mm10_VM14"

